import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Main from "@/components/Main";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Ascendancy Paradox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Nav />
      <Header />
      <Navbar />
      <body className={`${inter.className} bg-[#000] overflow-y-scroll overflow-x-hidden `}>
      {children}
      </body>
    </html>
  );
}
